name: env-run
on:
  workflow_dispatch:
env:
  mongoDB: url

jobs:
  buildcheck:
    runs-on: ubuntu-latest
    environment: staging
    env:
      PORT: 8080
      MONGO_SECRETS: ${{secrets.MONGO_CLUSTER}}
    steps:
      - name: compile data
        run: "echo test data ${{env.mongoDB}}"
      - name: test data
        run: "echo test $PORT"

      - name: Secret Manger env-run
        run: "echo ${env.MONGO_CLUSTER}"
  compilationdata:
    runs-on: ubuntu-latest
    environment: dev1
    steps:
      - name: dev data
        run: "echo ${env.MONGO_CLUSTER}"
